import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class ArticleListItemService {

  constructor() { }
  //Article list Item
    articleListItem = [{
      id: 1,
      title: 'Huge Drama at The Game Awards',
      subTitle:'The show, which is hosted by video game journalist and personality Geoff Keighley, features a number of awards categories, including Game of the Year, Best Indie Game, and Best Mobile Game.',
      articleImage:'assets/images/gameawards.gif',
      link:'https://www.youtube.com/watch?v=MnXSgZuvvzc&t=1s',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',

    },
    {
      id: 2,
      title: 'This New Livestreaming Platform Might Be a Scam',
      subTitle:'First released in 1999, Super Smash Bros. has grown to become one of the most iconic and enduring franchises in the world of gaming.',
      articleImage:'assets/images/livestreaming.gif',
      link:'https://www.youtube.com/watch?v=FSfmEBGivkQ&t=1s',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 3,
      title: 'Should Twitch Streamers Pay Their Moderators',
      subTitle:'Twitch streamers should pay their moderators if they are able to do so. Moderators help keep the streamers chat organized and free from spam, trolls, and other disruptive behavior, which can be a valuable service for a streamer. ',
      articleImage:'assets/images/mods.gif',
      link:'https://www.youtube.com/watch?v=zA-i7WtnvVo',
     art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 4,
      title: 'Amouranth is a Victim of Abuse',
      subTitle:'Abuse is the improper or excessive use of something, or the mistreatment of a person or animal. It can take many forms, including physical, sexual, emotional, and verbal.',
      articleImage:'assets/images/ammo.gif',
      link:'https://www.youtube.com/watch?v=aq2uQHcZt8U',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 5,
      title: 'Huge Cheating Scandal',
      subTitle:'Popular Call of Duty streamer Nadia Amine is playing from a “clean PC” to squash relentless allegations that she\'s cheating with aimbots',
      articleImage:'assets/images/scandal.gif',
      link:'https://www.youtube.com/watch?v=jRlsS4-IXBo&t=325s',
     art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 6,
      title: 'LeBron James is a Liar',
      subTitle:'Jalen Ramsey hilariously calls out LeBron James for lying, just like everyone on Twitter ... On Thursday night,',
      articleImage:'assets/images/lebron.gif',
      link:'https://www.youtube.com/watch?v=0MlR4uytW78',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 7,
      title: 'Huge Drama at the ChessBoxing Event',
      subTitle:'Chess boxing is a hybrid sport that combines the strategic elements of chess with the physical training and discipline of boxing. The sport was first conceptualized by Dutch artist Iepe Rubingh in 2003 and has since gained popularity in various countries around the world.',
      articleImage:'assets/images/chess.gif',
      link:'https://www.youtube.com/watch?v=WV38uDXHKz0',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 8,
      title: 'Streamer Accidentally Exposes a Scam',
      subTitle:'A scam is a fraudulent scheme or deception that is used to obtain money or other benefits from someone. Scams can take many forms, including letters, phone calls, emails, or online advertisements, and may be designed to trick people into giving away sensitive information, such as personal or financial details, or to make them believe they are entitled to a prize or other reward.',
      articleImage:'assets/images/scam.gif',
      link:'https://www.youtube.com/watch?v=gmEYQ4hDys8',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    },{
      id: 9,
      title: 'The Most Dangerous Man in America',
      subTitle:'FTX is a cryptocurrency derivatives exchange that was founded in 2019. It offers a range of products including futures, options, and spot trading on a wide variety of digital assets. The platform is known for its user-friendly interface and advanced trading tools, as well as its liquidity and fast execution speeds. ',
      articleImage:'assets/images/man.gif',
      link:'https://www.youtube.com/watch?v=a5vT3zF0h7U',
      art:'Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.Lorem ipsum is a placeholder text commonly used to demonstrate the visual form of a document or a typeface. It is often used as filler text to help designers visualize the layout and formatting of a document or website. Lorem ipsum is derived from the Latin "dolorem ipsum," which translates to "pain itself." It is a placeholder text that has been used in the printing and typesetting industry for centuries. It is a useful tool for designers because it allows them to see how text will look in a layout without being distracted by the actual content of the text.',
    }];
}
